language: android
jdk:
- openjdk7
script:
- ./gradlew --daemon --stacktrace library:build
- 
- ./gradlew --daemon --stacktrace library:connectedCheck || (adb logcat -t 100 '*:E'
  && false)
env:
- TARGET=android-21 ABI=armeabi-v7a
android:
  components:
  - build-tools-21.1.1
  - android-21
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
before_install:
- chmod +x gradlew
- export TERM=dumb
- android list targets
- echo no | android create avd --force -n test -t $TARGET -b $ABI
- emulator -avd test -no-skin -no-audio -no-window &
- ./gradlew --daemon --stacktrace library:tasks
- android-wait-for-emulator
after_script:
- android delete avd -n test
notifications:
  slack:
    secure: fux0AWdJ6lwJA29jkqRPN+CJua+0fuy/4G3uV2pBPQ6BnYUR9ty9E+1Il2tLeDU0cBLXAkhzUcGj3SrHP+NdZQF3s7vst/7SOFpOK61zCW4qAtDxQ3sCs9oFOQD548bwVQHJuPxdnQ1mA8OMzve0+oDx/LaRglVo5quXtT+wHlA=
