language: android
jdk:
  - openjdk7
script:
  - export POWERASSERT_VERBOSE=2
  - ./gradlew --daemon --stacktrace library:build
  - # export COVERAGE=true
  - ./gradlew --daemon --stacktrace library:connectedCheck || (adb logcat -t 100 '*:E' && false)
env:
  - TARGET=android-10 ABI=armeabi
  - TARGET=android-21 ABI=armeabi-v7a
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    # The BuildTools version used by your project
    - build-tools-21.1.1
    # The SDK version used to compile your project
    - android-21
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
before_install:
  - chmod +x gradlew
  - export TERM=dumb # to get clean gradle output
  - android list targets # for debugging
  - echo no | android create avd --force -n test -t $TARGET -b $ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./gradlew --daemon --stacktrace tasks # install dependencies while the eumulator is booting
  - android-wait-for-emulator
after_script:
  - android delete avd -n test
